# Generated by Django 4.1.5 on 2023-02-07 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_productinventory_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='format : y-m-d H:M:S', verbose_name='date wishlist created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist_product', to='inventory.product', verbose_name='user wishlist product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist', to=settings.AUTH_USER_MODEL, verbose_name='user wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'the amount must be between 0 and 9999.99'}}, help_text='format : maximum amount 9999.99', max_digits=6, verbose_name='amount of credit')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format : y-m-d H:M:S', verbose_name='date wallet last updated')),
                ('user', models.OneToOneField(help_text='format : user that wallet belong to ,unique', on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL, verbose_name='user wallet')),
            ],
        ),
    ]
