# Generated by Django 4.1.5 on 2023-02-07 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='format : max-255', max_length=255, verbose_name='contact person name')),
                ('street', models.TextField()),
                ('apartment', models.TextField()),
                ('city', models.CharField(help_text='format : max-255', max_length=255, verbose_name=' city & state name')),
                ('is_default', models.BooleanField(default=False, help_text='format : true = default address for orders', verbose_name='default address')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='format : y-m-d H:M:S', verbose_name='date address created')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format : y-m-d H:M:S', verbose_name='date address last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='user address')),
            ],
        ),
    ]
