# Generated by Django 4.1.5 on 2023-02-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='contact person mobile number'),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='zip code'),
        ),
    ]
