export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const LOAD_CART = "LOAD_CART"
export const SAVE_LOCAL = "SAVE_LOCAL"
export const LOAD_LOCAL = "LOAD_LOCAL"
