# Generated by Django 4.1.5 on 2023-02-11 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productinventory_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='format : y-m-d H:M:S', verbose_name='date order created')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format : y-m-d H:M:S', verbose_name='date order last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='user cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='quantity of product')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='format : y-m-d H:M:S', verbose_name='date order created')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format : y-m-d H:M:S', verbose_name='date order last updated')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='checkout.cart', verbose_name='cart item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_product', to='inventory.product', verbose_name='cart item product')),
                ('variants', models.ManyToManyField(help_text='format : selected variants for cart', to='inventory.productattributevalue', verbose_name='product variants')),
            ],
        ),
    ]
