# Generated by Django 4.1.5 on 2023-02-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format : max-255', max_length=255, verbose_name='delivery name')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'the amount must be between 0 and 99999.99'}}, help_text='format : maximum amount 99999.99', max_digits=7, verbose_name='price of delivery')),
                ('max_weight', models.FloatField(verbose_name='maximum weight')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='format : y-m-d H:M:S', verbose_name='date payment created')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format : y-m-d H:M:S', verbose_name='date payment last updated')),
            ],
        ),
    ]
