# Generated by Django 4.1.5 on 2023-02-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='image',
            field=models.ImageField(blank=True, default='images/delivery/default.png', help_text='format : required , default-default.png', null=True, upload_to='images/delivery/', verbose_name='delivery image'),
        ),
    ]
