# Generated by Django 4.1.5 on 2023-03-30 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0008_historypayment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history_payment', to=settings.AUTH_USER_MODEL, verbose_name='user order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('UNCONFIRMED', 'UnConfirmed'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', help_text='format : Pending = Order received, no payment initiated , Failed = Payment failed or was declined (unpaid) , Processing =  Payment received (paid) and stock has been reduced; order is awaiting fulfillment , Completed = Order fulfilled and complete', max_length=255, null=True, verbose_name='order status'),
        ),
        migrations.DeleteModel(
            name='HistoryPayment',
        ),
    ]
