# Generated by Django 4.1.5 on 2023-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderpayment_client_secret_orderpayment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('UNCONFIRMED', 'UnConfirmed'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='UNCONFIRMED', help_text='format : Pending = Order received, no payment initiated , Failed = Payment failed or was declined (unpaid) , Processing =  Payment received (paid) and stock has been reduced; order is awaiting fulfillment , Completed = Order fulfilled and complete', max_length=255, null=True, verbose_name='order status'),
        ),
    ]
