# Generated by Django 4.1.5 on 2023-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productinventory_attribute_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_attribute_values', through='inventory.ProductAttributeValues', to='inventory.productattributevalue'),
        ),
    ]
