# Generated by Django 4.1.5 on 2023-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_stock_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_recommend',
            field=models.BooleanField(default=False, help_text='format : true=you recommend this product to customer', verbose_name='you recommend'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, help_text='format : true=this product for some reason is special', verbose_name='special product'),
        ),
    ]
